import {NextRequest,NextResponse} from 'next/server';import dns from 'node:dns/promises';import net from 'node:net';import {getSession} from '@/lib/session';import {listPosts,getOwnedBlog} from '@/lib/blogger';import {getEntitlement} from '@/lib/subscription';
function isPrivateV4(ip:string){const [a,b]=ip.split('.').map(Number);return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127);}
function privateIp(ip:string){if(net.isIPv4(ip))return isPrivateV4(ip);if(net.isIPv6(ip)){const x=ip.toLowerCase();
  // Unwrap IPv4-mapped/compatible IPv6 addresses (::ffff:a.b.c.d, ::a.b.c.d) so they
  // can't be used to sneak a private/link-local IPv4 target past this filter.
  const mapped=x.match(/^::(?:ffff:)?(\d+\.\d+\.\d+\.\d+)$/);
  if(mapped)return isPrivateV4(mapped[1]);
  return x==='::1'||x==='::'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe80:');
}return true;}
async function safeUrl(raw:string){let u:URL;try{u=new URL(raw)}catch{return null}if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return null;const host=u.hostname.toLowerCase();if(['localhost','localhost.localdomain'].includes(host)||host.endsWith('.local'))return null;try{const ips=(await dns.lookup(host,{all:true})).map((x:any)=>x.address);if(!ips.length||ips.some(privateIp))return null;}catch{return null}return u;}
export async function GET(req:NextRequest){const s=await getSession();if(!s)return NextResponse.json({error:'Connect your Google account first.'},{status:401});try{const e=await getEntitlement();const limit=e.plan==='FREE'?20:150;const blogId=req.nextUrl.searchParams.get('blogId')||s.blogId;if(!blogId)return NextResponse.json({links:[],scanned:0,limit});await getOwnedBlog(s,blogId);const p=await listPosts(s,blogId,{maxResults:100});const links:any[]=[];for(const post of p.items||[]){for(const m of String(post.content||'').matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>/gi)){if(links.length>=limit)break;links.push({url:m[1],source:post.title||post.id,postId:post.id});}if(links.length>=limit)break;}const results=[];for(const l of links){const u=await safeUrl(l.url);if(!u){results.push({...l,status:/^https?:\/\//i.test(l.url)?'Blocked':'Internal',responseTime:null,lastChecked:new Date().toISOString()});continue;}const start=Date.now();try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5000);const r=await fetch(u,{method:'HEAD',redirect:'manual',signal:controller.signal as any,headers:{'User-Agent':'WyBlog Link Checker/1.0'}});clearTimeout(timer);results.push({...l,status:r.status,responseTime:Date.now()-start,lastChecked:new Date().toISOString(),location:r.headers.get('location')||undefined});}catch{results.push({...l,status:'Timeout',responseTime:Date.now()-start,lastChecked:new Date().toISOString()});}}
return NextResponse.json({links:results,scanned:results.length,limit,limited:links.length>=limit});}catch{return NextResponse.json({error:'Unable to scan links right now.'},{status:500});}}
