'use client';
import {useEffect,useMemo,useRef,useState} from 'react';import {useRouter} from 'next/navigation';import Toast from './Toast';
const btns=[['B','bold'],['I','italic'],['U','underline'],['S','strikeThrough'],['H1','formatBlock:h1'],['H2','formatBlock:h2'],['H3','formatBlock:h3'],['H4','formatBlock:h4'],['Left','justifyLeft'],['Center','justifyCenter'],['Right','justifyRight'],['Justify','justifyFull'],['❝','formatBlock:blockquote'],['Code','formatBlock:pre'],['• List','insertUnorderedList'],['1. List','insertOrderedList'],['☑','insertUnorderedList'],['—','insertHorizontalRule'],['Link','createLink'],['Unlink','unlink'],['Image','insertImage'],['Table','table'],['Callout','callout'],['Button','button'],['Clear','removeFormat']];
function strip(s:string){return s.replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
export default function Editor({initial,blogId}:{initial:any;blogId?:string}){
 const router=useRouter(),ref=useRef<HTMLDivElement>(null);const key='wyblog-draft-'+(initial?.id||'new');
 const [title,setTitle]=useState(initial?.title||''),[seoTitle,setSeoTitle]=useState(initial?.seoTitle||initial?.title||''),[slug,setSlug]=useState(initial?.slug||''),[desc,setDesc]=useState(initial?.metaDescription||initial?.searchDescription||''),[keyword,setKeyword]=useState(initial?.focusKeyword||''),[labels,setLabels]=useState((initial?.labels||[]).join(', ')),[body,setBody]=useState(initial?.content||''),[toast,setToast]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[recover,setRecover]=useState<any>(null);
 useEffect(()=>{const raw=localStorage.getItem(key);if(raw){try{const d=JSON.parse(raw);const {savedAt,...draftContent}=d;if((d.title||d.body||d.desc)&&JSON.stringify(draftContent)!==JSON.stringify({title,seoTitle,slug,desc,keyword,labels,body}))setRecover(d)}catch{}}},[]);
 useEffect(()=>{if(ref.current&&!ref.current.innerHTML)ref.current.innerHTML=body||'<p>Start writing…</p>'},[]);
 useEffect(()=>{const t=setTimeout(()=>localStorage.setItem(key,JSON.stringify({title,seoTitle,slug,desc,keyword,labels,body,savedAt:Date.now()})),500);return()=>clearTimeout(t)},[title,seoTitle,slug,desc,keyword,labels,body,key]);
 const stats=useMemo(()=>{const t=strip(body),w=t?t.split(/\s+/).length:0;return{w,chars:t.length,read:Math.max(1,Math.ceil(w/220))}},[body]);
 function sync(){const html=ref.current?.innerHTML||body;setBody(html);return html}
 async function save(){setSaving(true);setSaved(false);try{const html=sync();const r=await fetch('/api/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:initial?.id,blogId:blogId||initial?.blogId,title,slug,metaDescription:desc,focusKeyword:keyword,labels:labels.split(',').map(x=>x.trim()).filter(Boolean),content:html})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save article.');setSaved(true);setToast('Article saved');localStorage.removeItem(key);if(d.post?.id&&d.post.id!==initial?.id){router.replace('/app/posts/'+d.post.id+'/edit');}return d.post}catch(e:any){setToast(e.message||'Could not save article.');return null}finally{setSaving(false)}}
 async function diagnose(){const post=await save();if(post?.id)router.push('/app/posts/'+post.id+'/diagnose')}
 function cmd(c:string){if(c.startsWith('formatBlock:'))document.execCommand('formatBlock',false,c.split(':')[1]);else if(c==='createLink'){const u=prompt('Enter the full link URL');if(u&&/^https?:\/\//i.test(u))document.execCommand('createLink',false,u);else if(u)setToast('Please enter a full http(s) URL.')}else if(c==='insertImage'){const u=prompt('Image URL');if(u&&/^https?:\/\//i.test(u)){document.execCommand('insertImage',false,u);setTimeout(()=>{ref.current?.querySelectorAll('img').forEach((img:any)=>{if(!img.alt)img.alt=prompt('ALT text for this image')||''})},0)}}else if(c==='table'){document.execCommand('insertHTML',false,'<table><tbody><tr><td>Cell</td><td>Cell</td></tr><tr><td>Cell</td><td>Cell</td></tr></tbody></table>')}else if(c==='callout'){document.execCommand('insertHTML',false,'<aside style=\"padding:14px;border:1px solid #d0d5dd;border-radius:10px;margin:16px 0\"><strong>Callout</strong><p>Important information.</p></aside>')}else if(c==='button'){const u=prompt('Button URL');const label=prompt('Button text')||'Read more';if(u&&/^https?:\/\//i.test(u))document.execCommand('insertHTML',false,`<p><a href=\"${u}\" rel=\"nofollow\">${label}</a></p>`)}else document.execCommand(c,false);sync()}
 function recoverDraft(){if(!recover)return;setTitle(recover.title||'');setSeoTitle(recover.seoTitle||recover.title||'');setSlug(recover.slug||'');setDesc(recover.desc||'');setKeyword(recover.keyword||'');setLabels(recover.labels||'');setBody(recover.body||'');if(ref.current)ref.current.innerHTML=recover.body||'<p>Start writing…</p>';setRecover(null);setToast('Unsaved draft recovered')}
 return <div>{recover&&<div className="notice"><b>Recover unsaved article?</b><p className="muted">A local draft from your last session was found.</p><button className="btn btn-primary" onClick={recoverDraft}>Recover</button> <button className="btn" onClick={()=>{localStorage.removeItem(key);setRecover(null)}}>Discard</button></div>}
 <div className="page-head"><div><h1>{initial?.id?'Edit article':'New article'}</h1><div className="muted">{saving?'Saving…':saved?'Saved to Blogger as draft':'Autosave recovery enabled'}</div></div><div className="actions"><button className="btn" disabled={saving} onClick={save}>Save draft</button><button className="btn btn-primary" disabled={saving} onClick={diagnose}>Save & diagnose</button></div></div>
 <div className="editor-layout"><section><div className="card"><input className="editor-title" placeholder="Article title" value={title} onChange={e=>setTitle(e.target.value)}/><div className="grid grid-2"><div className="field"><label>SEO title</label><input value={seoTitle} onChange={e=>setSeoTitle(e.target.value)}/><small className="muted">Blogger's public title remains the article title.</small></div><div className="field"><label>Suggested URL slug</label><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="blogger-generated-url-slug"/></div></div><div className="field"><label>Meta description</label><textarea className="textarea" value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Describe this article for searchers…"/></div><div className="field"><label>Focus keyword</label><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="Optional"/></div><div className="toolbar">{btns.map(([label,c])=><button key={label} type="button" className="btn" onMouseDown={e=>e.preventDefault()} onClick={()=>cmd(c)}>{label}</button>)}</div><div ref={ref} className="editor-body" contentEditable suppressContentEditableWarning onInput={sync} onBlur={sync}/><div className="grid grid-3" style={{marginTop:14}}><div className="field"><label>Labels</label><input value={labels} onChange={e=>setLabels(e.target.value)}/></div><div className="field"><label>Status</label><input value={initial?.status==='LIVE'?'Published':'Draft'} readOnly/></div><div className="field"><label>Author</label><input value={initial?.author||'You'} readOnly/></div></div><div className="sticky-actions"><button className="btn" disabled={saving} onClick={save}>Save</button><button className="btn btn-primary" disabled={saving} onClick={diagnose}>Diagnose before publishing</button></div></div></section><aside><SeoMini title={title} desc={desc} slug={slug} keyword={keyword} body={body}/></aside></div>{toast&&<Toast message={toast} onDone={()=>setToast('')}/>}</div>
}
function SeoMini({title,desc,slug,keyword,body}:{title:string;desc:string;slug:string;keyword:string;body:string}){const text=strip(body),w=text?text.split(/\s+/).length:0;const checks=[['Title',!!title,title?'Title exists':'Add a title'],['Title length',title.length>=30&&title.length<=65,`${title.length} chars`],['Meta',!!desc,desc?'Description added':'Add a meta description'],['URL',/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug),slug?'Readable slug':'Create a clean slug'],['Keyword',!keyword||title.toLowerCase().includes(keyword.toLowerCase()),keyword?'Keyword in title':'No focus keyword'],['Content',w>=600,`${w} words`],['H1',(body.match(/<h1\b/gi)||[]).length===1,'Exactly one H1']];const score=Math.round(checks.filter(x=>x[1]).length/checks.length*100);return <div className="card"><b>SEO SCORE</b><div className="metric">{score}/100</div><div className="progress" style={{margin:'10px 0 14px'}}><div style={{width:`${score}%`}}/></div>{checks.map(([n,ok,m])=><div className="seo-item" key={String(n)}><span className="check">{ok?'✓':'!'}</span><span><b>{n}</b><br/><span className={ok?'status-good':'status-warn'}>{String(m)}</span></span></div>)}<div className="notice" style={{marginTop:12}}>Word count {w} · {Math.max(1,Math.ceil(w/220))} min read · {text.length} characters</div></div>}
